
-- Create incident_comments table
create table public.incident_comments (
  id bigint generated by default as identity primary key,
  incident_id bigint references public.incidents(id) on delete cascade not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_email text -- Optional: store who commented if auth is available, currently we might just store 'System' or 'User'
);

create index incident_comments_incident_id_idx on public.incident_comments(incident_id);
alter table public.incident_comments enable row level security;
create policy "Public incident_comments access" on public.incident_comments for all using (true);
