
-- Add password column to status_pages
alter table public.status_pages 
add column if not exists password text;

-- Create junction table for Status Page <-> Monitors
create table public.status_page_monitors (
  id bigint generated by default as identity primary key,
  status_page_id uuid references public.status_pages(id) on delete cascade not null,
  monitor_id uuid references public.monitors(id) on delete cascade not null,
  unique(status_page_id, monitor_id)
);

create index status_page_monitors_page_id_idx on public.status_page_monitors(status_page_id);
alter table public.status_page_monitors enable row level security;
create policy "Public status_page_monitors access" on public.status_page_monitors for all using (true);
