
-- Maintenance Windows
create table public.maintenance_windows (
  id uuid default gen_random_uuid() primary key,
  title text not null,
  start_time timestamp with time zone not null,
  end_time timestamp with time zone not null,
  status text default 'scheduled' check (status in ('scheduled', 'active', 'completed')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.maintenance_windows enable row level security;
create policy "Public maintenance_windows access" on public.maintenance_windows for all using (true);

-- Maintenance - Monitor Junction (Many-to-Many)
create table public.maintenance_monitors (
  id bigint generated by default as identity primary key,
  maintenance_id uuid references public.maintenance_windows(id) on delete cascade not null,
  monitor_id uuid references public.monitors(id) on delete cascade not null
);
alter table public.maintenance_monitors enable row level security;
create policy "Public maintenance_monitors access" on public.maintenance_monitors for all using (true);

-- Team Members
create table public.team_members (
  id uuid default gen_random_uuid() primary key,
  email text not null,
  role text default 'member' check (role in ('owner', 'admin', 'member', 'viewer')),
  status text default 'invited' check (status in ('active', 'invited')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.team_members enable row level security;
create policy "Public team_members access" on public.team_members for all using (true);

-- Integrations
create table public.integrations (
  id uuid default gen_random_uuid() primary key,
  type text not null check (type in ('webhook', 'slack', 'discord', 'telegram')),
  name text,
  config jsonb not null, -- Stores url, secrets, etc
  events text[] default '{}', -- Array of events to subscribe to: ['down', 'up', 'incident']
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.integrations enable row level security;
create policy "Public integrations access" on public.integrations for all using (true);
