-- Create monitors table
create table public.monitors (
  id uuid default gen_random_uuid() primary key,
  user_id uuid default auth.uid(), -- Optional: for RLS if you add auth later
  name text not null,
  url text,
  type text not null check (type in ('http', 'ping', 'keyword', 'port')),
  interval int default 60, -- Check interval in seconds
  status text default 'up' check (status in ('up', 'down', 'paused')),
  last_checked timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create heartbeats table for history
create table public.heartbeats (
  id bigint generated by default as identity primary key,
  monitor_id uuid references public.monitors(id) on delete cascade not null,
  status text not null check (status in ('up', 'down')),
  latency int, -- Response time in ms
  timestamp timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create indexes
create index monitors_user_id_idx on public.monitors(user_id);
create index heartbeats_monitor_id_timestamp_idx on public.heartbeats(monitor_id, timestamp desc);

-- Enable RLS (Row Level Security) - Optional but recommended
alter table public.monitors enable row level security;
alter table public.heartbeats enable row level security;

-- Create policies (Allow public access for now since there is no auth yet, 
-- BUT THIS IS INSECURE FOR PRODUCTION. Update when Auth is added.)
create policy "Public monitors access" on public.monitors for all using (true);
create policy "Public heartbeats access" on public.heartbeats for all using (true);
